# Generated by Django 4.2.6 on 2023-11-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='nombre',
            new_name='cate_desc',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='descripcion',
            new_name='cate_estado',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='id',
            new_name='cate_id',
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_desc', models.CharField(max_length=100, verbose_name='Nombre')),
                ('prod_vu', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('prod_estado', models.TextField(max_length=2)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruver.categorias', verbose_name='Categoria')),
            ],
        ),
    ]
