# Generated by Django 4.2.6 on 2023-11-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruver', '0002_rename_nombre_categorias_cate_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='prod_estado',
            field=models.TextField(max_length=2, verbose_name='Estado'),
        ),
    ]
