# Generated by Django 4.2.6 on 2023-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruver', '0003_alter_productos_prod_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='cate_desc',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='cate_estado',
            field=models.TextField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_desc',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_vu',
            field=models.TextField(max_length=100, verbose_name='Valor unitario'),
        ),
    ]
